/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.admin;

import model.SupplierDirectory;
import model.Supplier;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author lingduan
 */
public class ManageSuppliers extends javax.swing.JPanel {

    JPanel workArea;
    SupplierDirectory supplierDirectory;
    private Object tblSuppliers;
    /**
     * Creates new form ManageSuppliers
     */
    public ManageSuppliers(JPanel workArea, SupplierDirectory supplierDirectory) {
        initComponents();
         this.workArea = workArea;
        this.supplierDirectory = supplierDirectory;
        
        refreshTable(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSupplierName = new javax.swing.JTable();
        btnAddSupplier = new javax.swing.JButton();
        btnViewSupplier = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();

        lblTitle.setText("Manage Suppliers:");

        tblSupplierName.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null}
            },
            new String [] {
                "Supplier Name"
            }
        ));
        tblSupplierName.setShowGrid(true);
        tblSupplierName.setShowVerticalLines(false);
        jScrollPane1.setViewportView(tblSupplierName);

        btnAddSupplier.setText("Add Supplier");
        btnAddSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSupplierActionPerformed(evt);
            }
        });

        btnViewSupplier.setText("View Supplier");
        btnViewSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewSupplierActionPerformed(evt);
            }
        });

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(btnAddSupplier)
                        .addGap(76, 76, 76)
                        .addComponent(btnViewSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddSupplier)
                    .addComponent(btnViewSupplier)
                    .addComponent(btnRemove))
                .addContainerGap(198, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSupplierActionPerformed
        // TODO add your handling code here:
        String supplierName = JOptionPane.showInputDialog("Enter Supplier Name:");

        if (supplierName != null && !supplierName.trim().isEmpty()) {
            Supplier newSupplier = new Supplier(supplierName);  // Create a new Supplier object
            supplierDirectory.addSupplier(newSupplier);  // Add the new supplier to the directory
            refreshTable();  // Refresh the table
        } else {
            JOptionPane.showMessageDialog(this, "Supplier name cannot be empty!", "Error", JOptionPane.ERROR_MESSAGE);
        } 
        
       
    }//GEN-LAST:event_btnAddSupplierActionPerformed

    private void btnViewSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSupplierActionPerformed
        // TODO add your handling code here:
         int selectedRow = tblSupplierName.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a supplier to view", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String supplierName = (String) tblSupplierName.getValueAt(selectedRow, 0);
        Supplier selectedSupplier = supplierDirectory.searchSupplier(supplierName);  // Assuming you have searchSupplier() method
        
        if (selectedSupplier != null) {
            // Create and show the View Supplier Details panel
            ViewSupplier viewPanel = new ViewSupplier(workArea, selectedSupplier);
            workArea.add("ViewSupplierJPanel", viewPanel);
            CardLayout layout = (CardLayout) workArea.getLayout();
            layout.next(workArea);
        }
        
        
        
        
        
    }//GEN-LAST:event_btnViewSupplierActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblSupplierName.getSelectedRow();
    if (selectedRow < 0) {
        JOptionPane.showMessageDialog(this, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Get the supplier name from the selected row
    String supplierName = (String) tblSupplierName.getValueAt(selectedRow, 0);

    // Remove the selected supplier from the supplier directory
    supplierDirectory.removeSupplier(supplierName);  // Assuming you have a removeSupplier method

    // Refresh the table to update the view
    refreshTable();
}
    
    

    private void refreshTable() {
        DefaultTableModel model = (DefaultTableModel) tblSupplierName.getModel();
        model.setRowCount(0);  // Clear the table

        for (Supplier s : supplierDirectory.getSupplierList()) {
            Object[] row = new Object[1];
            row[0] = s.getSupplierName();  // Assuming Supplier class has a getSupplierName() method
            model.addRow(row);  // Add rows to the table
        }
    }
        
        
        
    }//GEN-LAST:event_btnRemoveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSupplier;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnViewSupplier;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblSupplierName;
    // End of variables declaration//GEN-END:variables



